/**
 * English texts of the Assurance-Vie UI (`av_*`). The full 9-language set lives in
 * .tmp-av-keys.json until it is merged into the i18n files; until a key is merged `t()` returns
 * the key itself and `useAssuranceVieText` falls back to the English below, so the UI never shows raw keys.
 */
export const AV_EN = {
  "av_details_heading": "Life insurance contract (Assurance-Vie)",
  "av_insurer": "Insurer",
  "av_contract_name": "Contract name",
  "av_contract_number": "Contract number (optional)",
  "av_opened_on": "Contract opening date",
  "av_opened_on_hint": "The 8-year milestone is counted from this date, not from each premium.",
  "av_household": "Tax household status",
  "av_household_single": "Single filer",
  "av_household_couple": "Couple taxed jointly (married or PACS)",
  "av_household_single_short": "single filer",
  "av_household_couple_short": "jointly taxed couple",
  "av_household_hint": "Only used to pick the annual allowance shown after 8 years.",
  "av_alloc_heading": "Fund allocation",
  "av_euro_fund": "Euro fund (Fonds en euros)",
  "av_euro_fund_hint": "The capital guarantee is given by the insurer and usually applies net of management fees.",
  "av_uc": "Unit-linked (Unités de compte)",
  "av_uc_hint": "Market-linked: no capital guarantee, the value can go down as well as up.",
  "av_alloc_note": "The two shares always add up to 100%.",
  "av_alloc_total": "Total: {total}%",
  "av_implied": "Implied amount: {amount}",
  "av_alloc_bar_aria": "Allocation: {euro}% euro fund, {uc}% unit-linked",
  "av_deposits_heading": "Premiums (versements)",
  "av_deposit_type": "Deposit type",
  "av_deposit_free": "Free premiums (Versements libres)",
  "av_deposit_scheduled": "Scheduled premiums (Versements programmés)",
  "av_premiums_total": "Total premiums paid (optional)",
  "av_scheduled_amount": "Amount per premium",
  "av_scheduled_frequency": "Frequency",
  "av_freq_monthly": "Monthly",
  "av_freq_quarterly": "Quarterly",
  "av_freq_yearly": "Yearly",
  "av_scheduled_day": "Day of the month",
  "av_scheduled_start": "Start date (optional)",
  "av_scheduled_end": "End date (optional)",
  "av_scheduled_hint": "Recorded for reference only. Nothing is scheduled or debited from here.",
  "av_age70_heading": "Premiums by age when paid (optional)",
  "av_premiums_before_70": "Paid before age 70",
  "av_premiums_after_70": "Paid after age 70",
  "av_age70_hint": "Only used for an informational note. No estate tax is computed.",
  "av_bene_heading": "Designated beneficiaries (optional)",
  "av_bene_privacy": "These names are personal data about third parties. They are stored only in this asset's record and are visible to anyone this asset is shared with.",
  "av_bene_name": "Beneficiary name",
  "av_bene_relationship": "Relationship",
  "av_bene_share": "Share (%)",
  "av_bene_clause": "Clause type",
  "av_clause_standard": "Standard clause",
  "av_clause_free": "Free-text clause",
  "av_bene_clause_text": "Clause wording",
  "av_bene_add": "Add a beneficiary",
  "av_bene_remove": "Remove beneficiary {n}",
  "av_bene_item": "Beneficiary {n}",
  "av_bene_total": "Shares total: {total}%",
  "av_warn_bene_total": "Beneficiary shares add up to {total}%, not 100%. You can still save.",
  "av_warn_premium_split": "Premiums before and after age 70 add up to more than the total premiums paid.",
  "av_err_invalid": "The contract details are not valid.",
  "av_err_opened_invalid": "Enter a valid contract opening date.",
  "av_err_opened_future": "The opening date cannot be in the future.",
  "av_err_allocation_range": "Each allocation share must be between 0 and 100%.",
  "av_err_allocation_total": "The euro fund and unit-linked shares must add up to 100%.",
  "av_err_premium_negative": "Premium amounts must be zero or more.",
  "av_err_scheduled_amount": "Enter the amount of each scheduled premium.",
  "av_err_scheduled_frequency": "Choose how often the scheduled premium is paid.",
  "av_err_scheduled_day": "Enter a day of the month between 1 and 31.",
  "av_err_scheduled_dates": "Check the scheduled premium dates: they must be valid and the end must not be before the start.",
  "av_err_bene_count": "You can record up to 20 beneficiaries.",
  "av_err_bene_name": "Give each beneficiary a name, or remove the row.",
  "av_err_bene_share": "Each beneficiary share must be between 0 and 100%.",
  "av_summary_title": "Contract summary",
  "av_contract_value": "Total contract value",
  "av_alloc_title": "Allocation",
  "av_deposits_title": "Premiums",
  "av_scheduled_summary": "{frequency}: {amount}, on day {day} of the month",
  "av_scheduled_annual": "About {amount} per year",
  "av_milestone_title": "8-year milestone",
  "av_ms_unset": "Add the contract opening date to see the 8-year milestone.",
  "av_ms_badge_before": "Before 8 years",
  "av_ms_badge_reached": "8 years reached",
  "av_ms_anniversary": "8th anniversary: {date}",
  "av_ms_days_remaining": "Days remaining",
  "av_ms_months_remaining": "Whole months remaining",
  "av_ms_days_since": "Days since the anniversary",
  "av_ms_before_text": "From the 8th anniversary, the gains part of withdrawals (rachats) may benefit from an annual allowance (abattement) of {amount} ({household}).",
  "av_ms_reached_title": "Annual allowance on the gains part of withdrawals",
  "av_ms_reached_text": "After 8 years, each year the gains part of withdrawals (rachats) benefits from an annual allowance (abattement) of {amount} ({household}). It applies to the gains portion only: it is not a general capital-gains exemption and does not exempt the whole contract.",
  "av_ms_disclaimer": "Informational only, not tax advice. The allowance and French social levies concern French tax residents and depend on your tax residency and the rules in force. Check current rules. Figures as of {asOf}.",
  "av_age70_note": "Premiums paid before and after age 70 can fall under different allowance regimes. No amounts are computed here.",
  "av_bene_title": "Beneficiaries",
  "av_bene_none": "No beneficiaries recorded.",
  "av_scope_note": "The asset value is the total contract value. Unit-linked holdings, ISINs and live pricing are not tracked.",
} as const;

export type AvKey = keyof typeof AV_EN;
