/**
 * English texts of the Assurance-Vie UI (`av_*`). The full 9-language set of the contract holdings keys (`av_hold_*`) lives in
 * tmp-i18n-av-holdings.json until it is merged into the i18n files; until a key is merged `t()` returns
 * the key itself and `useAssuranceVieText` falls back to the English below, so the UI never shows raw keys.
 */
export const AV_EN = {
  "av_details_heading": "Life insurance contract (Assurance-Vie)",
  "av_insurer": "Insurer",
  "av_contract_name": "Contract name",
  "av_contract_number": "Contract number (optional)",
  "av_opened_on": "Contract opening date",
  "av_opened_on_hint": "The 8-year milestone is counted from this date, not from each premium.",
  "av_household": "Tax household status",
  "av_household_single": "Single filer",
  "av_household_couple": "Couple taxed jointly (married or PACS)",
  "av_household_single_short": "single filer",
  "av_household_couple_short": "jointly taxed couple",
  "av_household_hint": "Only used to pick the annual allowance shown after 8 years.",
  "av_alloc_heading": "Fund allocation",
  "av_euro_fund": "Euro fund (Fonds en euros)",
  "av_euro_fund_hint": "The capital guarantee is given by the insurer and usually applies net of management fees.",
  "av_uc": "Unit-linked (Unités de compte)",
  "av_uc_hint": "Market-linked: no capital guarantee, the value can go down as well as up.",
  "av_alloc_note": "The two shares always add up to 100%.",
  "av_alloc_total": "Total: {total}%",
  "av_implied": "Implied amount: {amount}",
  "av_alloc_bar_aria": "Allocation: {euro}% euro fund, {uc}% unit-linked",
  "av_deposits_heading": "Premiums (versements)",
  "av_deposit_type": "Deposit type",
  "av_deposit_free": "Free premiums (Versements libres)",
  "av_deposit_scheduled": "Scheduled premiums (Versements programmés)",
  "av_premiums_total": "Total premiums paid (optional)",
  "av_scheduled_amount": "Amount per premium",
  "av_scheduled_frequency": "Frequency",
  "av_freq_monthly": "Monthly",
  "av_freq_quarterly": "Quarterly",
  "av_freq_yearly": "Yearly",
  "av_scheduled_day": "Day of the month",
  "av_scheduled_start": "Start date (optional)",
  "av_scheduled_end": "End date (optional)",
  "av_scheduled_hint": "Recorded for reference only. Nothing is scheduled or debited from here.",
  "av_age70_heading": "Premiums by age when paid (optional)",
  "av_premiums_before_70": "Paid before age 70",
  "av_premiums_after_70": "Paid after age 70",
  "av_age70_hint": "Only used for an informational note. No estate tax is computed.",
  "av_bene_heading": "Designated beneficiaries (optional)",
  "av_bene_privacy": "These names are personal data about third parties. They are stored only in this asset's record and are visible to anyone this asset is shared with.",
  "av_bene_name": "Beneficiary name",
  "av_bene_relationship": "Relationship",
  "av_bene_share": "Share (%)",
  "av_bene_clause": "Clause type",
  "av_clause_standard": "Standard clause",
  "av_clause_free": "Free-text clause",
  "av_bene_clause_text": "Clause wording",
  "av_bene_add": "Add a beneficiary",
  "av_bene_remove": "Remove beneficiary {n}",
  "av_bene_item": "Beneficiary {n}",
  "av_bene_total": "Shares total: {total}%",
  "av_warn_bene_total": "Beneficiary shares add up to {total}%, not 100%. You can still save.",
  "av_warn_premium_split": "Premiums before and after age 70 add up to more than the total premiums paid.",
  "av_err_invalid": "The contract details are not valid.",
  "av_err_opened_invalid": "Enter a valid contract opening date.",
  "av_err_opened_future": "The opening date cannot be in the future.",
  "av_err_allocation_range": "Each allocation share must be between 0 and 100%.",
  "av_err_allocation_total": "The euro fund and unit-linked shares must add up to 100%.",
  "av_err_premium_negative": "Premium amounts must be zero or more.",
  "av_err_scheduled_amount": "Enter the amount of each scheduled premium.",
  "av_err_scheduled_frequency": "Choose how often the scheduled premium is paid.",
  "av_err_scheduled_day": "Enter a day of the month between 1 and 31.",
  "av_err_scheduled_dates": "Check the scheduled premium dates: they must be valid and the end must not be before the start.",
  "av_err_bene_count": "You can record up to 20 beneficiaries.",
  "av_err_bene_name": "Give each beneficiary a name, or remove the row.",
  "av_err_bene_share": "Each beneficiary share must be between 0 and 100%.",
  "av_summary_title": "Contract summary",
  "av_contract_value": "Total contract value",
  "av_alloc_title": "Allocation",
  "av_deposits_title": "Premiums",
  "av_scheduled_summary": "{frequency}: {amount}, on day {day} of the month",
  "av_scheduled_annual": "About {amount} per year",
  "av_milestone_title": "8-year milestone",
  "av_ms_unset": "Add the contract opening date to see the 8-year milestone.",
  "av_ms_badge_before": "Before 8 years",
  "av_ms_badge_reached": "8 years reached",
  "av_ms_anniversary": "8th anniversary: {date}",
  "av_ms_days_remaining": "Days remaining",
  "av_ms_months_remaining": "Whole months remaining",
  "av_ms_days_since": "Days since the anniversary",
  "av_ms_before_text": "From the 8th anniversary, the gains part of withdrawals (rachats) may benefit from an annual allowance (abattement) of {amount} ({household}).",
  "av_ms_reached_title": "Annual allowance on the gains part of withdrawals",
  "av_ms_reached_text": "After 8 years, each year the gains part of withdrawals (rachats) benefits from an annual allowance (abattement) of {amount} ({household}). It applies to the gains portion only: it is not a general capital-gains exemption and does not exempt the whole contract.",
  "av_ms_disclaimer": "Informational only, not tax advice. The allowance and French social levies concern French tax residents and depend on your tax residency and the rules in force. Check current rules. Figures as of {asOf}.",
  "av_age70_note": "Premiums paid before and after age 70 can fall under different allowance regimes. No amounts are computed here.",
  "av_bene_title": "Beneficiaries",
  "av_bene_none": "No beneficiaries recorded.",
  "av_estate_title": "Estate transfer: allowances by age at payment",
  "av_estate_intro": "French rules treat life-insurance premiums differently depending on the age of the insured when each premium was paid. These figures are shown for context only.",
  "av_estate_before70": "Premiums paid before age 70 (article 990 I): an allowance of {amount} per beneficiary, across all of the insured's contracts together.",
  "av_estate_after70": "Premiums paid after age 70 (article 757 B): one overall allowance of {amount}, shared by all beneficiaries, across all of the insured's contracts together. Only the premiums count against it; the gains they produced are outside it.",
  "av_estate_no_bene": "Name the beneficiaries above to see how many people share these allowances.",
  "av_estate_arith_before": "Named beneficiaries: {count}. {per} x {count} = {total} of allowance in total (one per beneficiary).",
  "av_estate_arith_after": "Named beneficiaries: {count}. {overall} / {count} = {share} each if split equally. Illustration only: the allowance is overall, not per person.",
  "av_estate_disclaimer": "Informational, not tax advice. It depends on the contract and on tax residency (UAE residents are treated differently). Check current rules. Figures as of {asOf}. Nothing is claimed here and no tax amount is computed.",
  "av_scope_note": "The asset value is the total contract value. Unit-linked holdings, ISINs and live pricing are not tracked.",
  "av_hold_heading": "Contract holdings (optional)",
  "av_hold_intro": "List what the contract holds, each value in the contract currency. When holdings are entered, the euro-fund and unit-linked percentages are calculated from them.",
  "av_hold_eligibility": "Which supports you can hold depends on the contract (insurer, French or Luxembourg, standard or private banking). Check the contract's list of eligible supports. Nothing is looked up online.",
  "av_hold_type": "Type",
  "av_hold_name": "Name",
  "av_hold_isin": "ISIN",
  "av_hold_ticker": "Ticker",
  "av_hold_units": "Units",
  "av_hold_unit_price": "Unit price",
  "av_hold_value": "Value",
  "av_hold_as_of": "As of",
  "av_hold_field_aria": "{field}, holding {n}",
  "av_hold_add": "Add holding",
  "av_hold_add_type": "Type of holding to add",
  "av_hold_remove": "Remove holding {n}",
  "av_hold_count": "{count} of {max} holdings",
  "av_hold_total": "Holdings total: {amount}",
  "av_hold_derived": "Calculated from the holdings: {euro}% euro fund, {uc}% unit-linked. Everything that is not the euro fund, including a cash balance, counts as unit-linked.",
  "av_hold_alloc_locked": "Calculated from the contract holdings. Remove the holdings to type the percentages yourself.",
  "av_hold_type_euro_fund": "Euro fund (Fonds en euros)",
  "av_hold_type_fund_opcvm": "Fund (OPCVM / SICAV / FCP)",
  "av_hold_type_etf": "ETF / tracker",
  "av_hold_type_scpi_sci_opci": "Real estate units (SCPI / SCI / OPCI)",
  "av_hold_type_private_equity_fund": "Private equity fund (FCPR / FPCI / FCPI)",
  "av_hold_type_structured_product": "Structured product",
  "av_hold_type_bond": "Bond",
  "av_hold_type_equity_direct": "Direct equity (titres vifs)",
  "av_hold_type_commodity_etc": "Commodity / gold ETC",
  "av_hold_type_money_market": "Money-market fund",
  "av_hold_type_cash_balance": "Cash balance (compte espèces)",
  "av_hold_type_other": "Other",
  "av_hold_recon_title": "Reconciliation with the contract value",
  "av_hold_recon_match": "The holdings total {holdings} matches the contract value {contract}.",
  "av_hold_recon_under": "The holdings total {holdings} is {difference} below the contract value {contract}.",
  "av_hold_recon_over": "The holdings total {holdings} is {difference} above the contract value {contract}.",
  "av_hold_recon_nocontract": "The holdings total {holdings}. Enter the contract value to compare it.",
  "av_hold_recon_note": "A difference is normal: values move between statements, and items such as fees, accrued interest or pending premiums may not be listed. You can still save.",
  "av_hold_warn_duplicate_isin": "The same ISIN appears more than once.",
  "av_hold_warn_value_mismatch": "For some holdings, units x unit price differs from the value entered.",
  "av_hold_err_invalid": "The holdings are not valid.",
  "av_hold_err_row": "One of the holdings is not valid.",
  "av_hold_err_count": "You can record up to 60 holdings.",
  "av_hold_err_type": "Choose a valid type for each holding.",
  "av_hold_err_name": "Give each holding a name, or remove the row.",
  "av_hold_err_value": "Enter a value of zero or more for each holding.",
  "av_hold_err_units": "Units must be zero or more.",
  "av_hold_err_price": "Unit price must be zero or more.",
  "av_hold_err_isin": "An ISIN has 12 characters: 2 letters, 9 letters or digits, then 1 digit.",
  "av_hold_err_date": "Enter a valid as-of date.",
  "av_hold_err_date_future": "The as-of date cannot be in the future.",
  "av_hold_title": "Contract holdings",
  "av_hold_by_type": "Breakdown by type",
  "av_hold_center": "POSITIONS",
  "av_hold_share": "Share",
  "av_hold_list": "Holdings",
  "av_hold_as_of_on": "As of {date}",
  "av_hold_card_note": "Holdings are shown at the amounts you entered. For a co-owned asset, the contract value above may be your share only.",
  "av_hold_scope_note": "The asset value is the total contract value. Holdings are entered by hand from the insurer's statements: there is no live pricing.",
} as const;

export type AvKey = keyof typeof AV_EN;
