/**
 * English texts of the Personal Cash Flow UI (`cf_*`). The full 9-language set lives in
 * `tmp-i18n-cashflow.json` until it is merged into the i18n files; until a key is merged `t()` returns
 * the key itself and `useCashFlowText` falls back to the English below, so the UI never shows raw keys.
 * The validation / action error codes of `lib/income-streams.ts` and the server actions are keys here too.
 */
export const CF_EN = {
  cf_nav: "Cash flow",
  cf_title: "Cash flow: income",
  cf_subtitle: "Your earned income streams. Enter what lands in your bank (net of tax and deductions).",
  cf_net_note: "Amounts are NET: what you actually receive.",
  cf_add: "Add income",
  cf_edit: "Edit {label}",
  cf_delete: "Delete {label}",
  cf_delete_confirm: "Delete \"{label}\"? This cannot be undone.",
  cf_delete_yes: "Delete",
  cf_table_caption: "Income streams",
  cf_col_label: "Stream",
  cf_col_kind: "Type",
  cf_col_amount: "Net amount",
  cf_col_freq: "Frequency",
  cf_col_when: "Pays on",
  cf_col_period: "Period",
  cf_col_monthly: "Per month ({currency})",
  cf_col_next: "Next 12 months ({currency})",
  cf_col_actions: "Actions",
  cf_kind_salary: "Salary",
  cf_kind_bonus: "Bonus",
  cf_kind_gratuity: "End-of-service gratuity",
  cf_kind_freelance: "Freelance",
  cf_kind_rental: "Rental",
  cf_kind_pension: "Pension",
  cf_kind_dividend_other: "Dividends and other",
  cf_kind_other: "Other",
  cf_freq_monthly: "Monthly",
  cf_freq_quarterly: "Quarterly",
  cf_freq_annual: "Annual",
  cf_freq_one_off: "One-off",
  cf_field_kind: "Type",
  cf_field_label: "Label",
  cf_field_source: "Source (employer, client...)",
  cf_field_amount: "Net amount per payment",
  cf_field_currency: "Currency",
  cf_field_frequency: "Frequency",
  cf_field_pay_day: "Pay day (1 to 31)",
  cf_field_pay_month: "Pay month",
  cf_field_pay_month_first: "First payment month",
  cf_field_start: "Start date",
  cf_field_end: "End date (optional)",
  cf_field_notes: "Notes (optional)",
  cf_pay_month_none: "Choose a month",
  cf_pay_day_hint: "Day 29 to 31 is moved to the last day of shorter months.",
  cf_ongoing: "Ongoing",
  cf_save: "Save",
  cf_saving: "Saving...",
  cf_cancel: "Cancel",
  cf_dialog_add: "Add an income stream",
  cf_dialog_edit: "Edit income stream",
  cf_dialog_desc: "Net amounts only: what lands in your bank account.",
  cf_totals_label: "Total",
  cf_totals_monthly: "Monthly equivalent",
  cf_totals_annual: "Next 12 months",
  cf_totals_note: "The monthly equivalent counts recurring streams that have not ended; one-off payments appear only in the 12-month total.",
  cf_empty: "No income streams yet.",
  cf_empty_hint: "Add your salary, bonus or other earned income to see it next to your passive income.",
  cf_unavailable: "Income streams are not available yet on this database.",
  cf_demo_note: "Demo mode: changes are not saved.",
  cf_cal_toggle: "Include earned income",
  cf_cal_view_label: "Calendar view",
  cf_cal_running_hint: "Running net: what you are ahead or behind by the end of this month, counted from the first month",
  cf_cal_day_by_day: "See this month day by day",
  cf_cal_open_full: "Open the full calendar: multi-year, charts and analysis",
  cf_cal_view_gross: "Gross income",
  cf_cal_view_liabilities: "Liabilities",
  cf_cal_view_net: "Net income",
  cf_cal_hover_earned: "Earned income",
  cf_cal_hover_gross: "Gross income",
  cf_cal_hover_liabilities: "Liabilities",
  cf_cal_hover_net: "Net income",
  cf_cal_liab_mortgage: "Mortgage",
  cf_cal_liab_loan: "Loan",
  cf_cal_liab_off_plan: "Off-plan property payments",
  cf_cal_liab_private_equity: "Private-equity capital calls",
  cf_cal_liab_credit_card: "Credit card",
  cf_cal_liab_other: "Other liabilities",
  cf_cal_liab_none: "No payment due this month.",
  cf_cal_net_note: "Net = gross income minus the payments due that month.",
  cf_cal_salary: "Salary",
  cf_cal_bonus: "Bonus",
  cf_cal_gratuity: "Gratuity",
  cf_cal_hover_passive: "Passive income",
  cf_field_employer: "Employer (one of your companies, or another)",
  cf_employer_other: "Another employer (type its name below)",
  cf_cal_other: "Other earned",
  cf_cal_earned_total: "Earned income, next 12 months: {amount}",
  cf_cal_earned_label: "Earned income",
  cf_salary: "Salary",
  cf_bonus: "Bonus",
  cf_investable_cash: "Investable cash",
  cf_emergency_fund: "Emergency fund",
  cf_err_kind: "Choose a type.",
  cf_err_label: "Enter a label of 1 to 120 characters.",
  cf_err_source: "The source must be 120 characters or fewer.",
  cf_err_amount: "Enter a net amount of zero or more.",
  cf_err_currency: "Choose a 3-letter currency code.",
  cf_err_frequency: "Choose a frequency.",
  cf_err_pay_day: "The pay day must be a whole number from 1 to 31.",
  cf_err_pay_month: "Choose the pay month.",
  cf_err_start: "Enter a valid start date.",
  cf_err_end: "The end date must be a valid date on or after the start date.",
  cf_err_notes: "Notes must be 2000 characters or fewer.",
  cf_err_signed_out: "You must be signed in.",
  cf_err_mfa: "Complete the two-step verification first.",
  cf_err_demo: "The demo account is read-only.",
  cf_err_not_found: "This income stream was not found.",
  cf_err_save_failed: "The income stream could not be saved. Try again.",
  cf_err_unavailable: "Income streams are not available yet on this database.",
} as const;

export type CashFlowKey = keyof typeof CF_EN;
