/**
 * English texts of the cash-flow waterfall and emergency fund panel (`cfw_*`). The nine-language set
 * lives in `tmp-i18n-waterfall.json` until it is merged into the i18n files; until a key is merged `t()`
 * returns the key itself and `useWaterfallText` falls back to the English below.
 */
export const CFW_EN = {
  cfw_title: "Cash-flow waterfall",
  cfw_subtitle: "From income to the money free to invest, on your own numbers.",
  cfw_informational: "Informational only, not financial advice.",
  cfw_stored_note: "Settings are kept in this browser.",
  cfw_reset: "Reset settings",
  cfw_empty: "Add income streams above and import your bank statements to see your waterfall.",
  cfw_ladder_title: "Monthly waterfall ({currency})",
  cfw_step_income: "Net income",
  cfw_step_liabilities: "Planned liabilities",
  cfw_step_expenses: "Daily life expenses",
  cfw_step_net: "Net investable cash",
  cfw_step_diversion: "To emergency fund",
  cfw_step_free: "Free to invest",
  cfw_why_no_income: "Add an income stream first.",
  cfw_why_no_expenses: "No transactions in the last {n} complete months. Import statements or enter an estimate.",
  cfw_why_no_net: "Needs income and expenses.",
  cfw_why_no_target: "Needs your essential expenses.",
  cfw_oneoff_note: "One-off income in the next 12 months ({amount}) is not part of the monthly figure.",
  cfw_velocity_title: "Cash-flow velocity, last 12 months",
  cfw_velocity_empty: "Not enough months with transactions to draw the line.",
  cfw_velocity_alt: "Net investable cash per month, {first} to {last}",
  cfw_ro_income: "Income",
  cfw_ro_liabilities: "Liabilities",
  cfw_ro_expenses: "Expenses",
  cfw_ro_net: "Net",
  cfw_settings_title: "Settings",
  cfw_set_lookback: "Months of expenses to average",
  cfw_set_months: "Emergency fund target (months)",
  cfw_set_pct: "Share of net investable cash diverted: {pct} %",
  cfw_set_manual: "Estimated monthly expenses ({currency})",
  cfw_set_manual_hint: "Used only while there are no imported transactions.",
  cfw_set_essential_pct: "Essential share of that estimate (%)",
  cfw_expenses_title: "Daily life expenses",
  cfw_exp_basis: "Average over {used} of {total} complete months that have transactions.",
  cfw_exp_basis_manual: "Your own estimate (no imported transactions).",
  cfw_exp_essential: "Essential",
  cfw_exp_discretionary: "Discretionary",
  cfw_exp_total: "Total per month",
  cfw_excl_title: "Excluded from expenses",
  cfw_excl_hint: "Switch an exclusion off to count those lines as expenses.",
  cfw_excl_ownTransfers: "Transfers between your own accounts",
  cfw_excl_liabilityPayments: "Payments of liabilities already counted",
  cfw_excl_cardSettlements: "Credit-card settlement lines",
  cfw_excl_desc_ownTransfers: "Opposite amounts on the same day in two of your accounts, or text such as \"between my accounts\".",
  cfw_excl_desc_liabilityPayments: "Lines close to a planned payment that name the lender or carry loan wording.",
  cfw_excl_desc_cardSettlements: "Lines such as \"credit card payment\", when the card statement is imported separately.",
  cfw_excl_count: "{count} lines, {amount} per month",
  cfw_merchants_title: "Biggest spending",
  cfw_col_merchant: "Merchant",
  cfw_col_monthly: "Per month",
  cfw_col_class: "Class",
  cfw_class_auto: "Automatic",
  cfw_class_essential: "Essential",
  cfw_class_discretionary: "Discretionary",
  cfw_merchant_override: "Class of {merchant}",
  cfw_ef_title: "Emergency fund (épargne de précaution)",
  cfw_ef_guidance: "Commonly cited guidance is 3 to 6 months of essential expenses: 3 as a usual minimum, 6 for a single or variable income. Informational, not advice.",
  cfw_ef_bar_label: "Emergency fund coverage",
  cfw_ef_target: "Target ({months} months)",
  cfw_ef_current: "Current",
  cfw_ef_gap: "Gap",
  cfw_ef_need: "Monthly need (essential + liabilities)",
  cfw_ef_progress: "{pct} % funded",
  cfw_ef_funded: "Funded: all of your net investable cash is free to invest.",
  cfw_ef_months_to_fund: "Months to fund",
  cfw_ef_diversion: "Diverted each month",
  cfw_ef_coverage: "Covers {n} months of essential costs and payments.",
  cfw_months_unit: "{n} mo",
  cfw_ef_accounts: "Accounts counted",
  cfw_ef_account_mark: "Count {name} as emergency fund",
  cfw_ef_not_liquid: "Not instant access",
  cfw_ef_no_accounts: "No Cash accounts yet.",
  cfw_ef_none_marked: "Tick the instant-access accounts that hold your emergency fund.",
  cfw_ef_why_no_months: "Net investable cash is zero or negative, so the fund does not grow.",
} as const;

export type WaterfallKey = keyof typeof CFW_EN;
