/**
 * English texts of the customisable-dashboard UI (`dlayout_*`). The full 9-language set lives in
 * .tmp-dlayout-keys.json until it is merged into the i18n files; until a key is merged `t()` returns
 * the key itself and `useDashboardLayoutText` falls back to the English below, so the UI never shows raw keys.
 */
export const DLAYOUT_EN = {
  "dlayout_customize": "Customize",
  "dlayout_customize_aria": "Customize the dashboard layout",
  "dlayout_done": "Done",
  "dlayout_cancel": "Cancel",
  "dlayout_reset": "Reset to default",
  "dlayout_banner_title": "Customizing your dashboard",
  "dlayout_hint": "Click a block to switch it on or off. Drag its handle or use the arrow buttons to move it, and pick a size.",
  "dlayout_sizes_hint": "Sizes apply on screens 1280 px wide and larger; smaller screens show one column.",
  "dlayout_state_on": "Active",
  "dlayout_state_off": "Inactive",
  "dlayout_drag_aria": "Drag to move {label}",
  "dlayout_move_up": "Move {label} up",
  "dlayout_move_down": "Move {label} down",
  "dlayout_size_group": "Size of {label}",
  "dlayout_size_s": "S",
  "dlayout_size_m": "M",
  "dlayout_size_l": "L",
  "dlayout_size_full": "Full",
  "dlayout_size_name_s": "Small, one third of the width",
  "dlayout_size_name_m": "Medium, half of the width",
  "dlayout_size_name_l": "Large, two thirds of the width",
  "dlayout_size_name_full": "Full width",
  "dlayout_status_saving": "Saving layout…",
  "dlayout_status_saved": "Layout saved",
  "dlayout_status_local": "Layout saved on this device only. It could not be saved to your account yet.",
  "dlayout_status_failed": "The layout could not be saved.",
  "dlayout_sr_instructions": "To move a block, focus its drag handle and press Space or Enter, then use the arrow keys to move it, Space or Enter to drop it, and Escape to cancel.",
  "dlayout_ann_start": "Picked up {label}.",
  "dlayout_ann_over": "{label} is now at position {position} of {total}.",
  "dlayout_ann_drop": "{label} dropped at position {position} of {total}.",
  "dlayout_ann_cancel": "Move cancelled. {label} is back at position {position}.",
  "dlayout_ann_on": "{label} switched on.",
  "dlayout_ann_off": "{label} switched off.",
  "dlayout_all_hidden": "Every block is switched off. Use Customize to bring blocks back.",
  "dlayout_no_data": "Nothing to show for this block right now.",
  "dlayout_block_fxExposure": "Global exposure",
  "dlayout_block_basicOverview": "Overview",
  "dlayout_block_bento": "Net worth highlights",
  "dlayout_block_allocation": "Allocation dial",
  "dlayout_block_quickAdd": "Quick add",
  "dlayout_block_metricCards": "Key figures",
  "dlayout_block_cashFlow": "Cash flow and accounts",
  "dlayout_block_incomeCalendar": "Income calendar",
  "dlayout_block_scpi": "SCPI",
  "dlayout_block_csvUpload": "Statement import",
  "dlayout_block_futureProjects": "Future projects",
  "dlayout_block_analytics": "Performance and analytics",
  "dlayout_block_portfolio": "Portfolio",
  "dlayout_block_expertRaw": "Raw data",
  "dlayout_block_expertPrivateEquity": "Private equity",
  "dlayout_block_expertTax": "Tax and depreciation",
  "dlayout_block_expertExposure": "Currency exposure",
  "dlayout_block_expertRatios": "Financial ratios",
  "dlayout_block_expertAttribution": "Currency vs capital",
  "dlayout_block_expertLiquidity": "Private-market liquidity",
  "dlayout_block_export": "Reports and export"
} as const;

export type DLayoutKey = keyof typeof DLAYOUT_EN;
