/**
 * English texts of the UAE gratuity UI (`grat_*`). The 9-language set lives in `tmp-i18n-gratuity.json`
 * until merged into the i18n files; until a key is merged `t()` returns the key and the hook falls back
 * to the English below (same pattern as `cash-flow-labels.ts`). Validation / action error codes are keys.
 */
export const GRAT_EN = {
  grat_title: "UAE end-of-service gratuity",
  grat_subtitle: "Estimate the gratuity owed to you, track what was already paid and see what is still outstanding.",
  grat_disclaimer:
    "Informational only, not legal advice. Based on Federal Decree-Law 33 of 2021 (Art. 51), rules as of {date}. Check your contract and ask the MOHRE or a lawyer.",
  grat_rules:
    "Basic wage only. 21 days per year for each of the first 5 years, 30 days per year after that, daily wage = basic / 30, capped at 24 months of basic wage, last basic wage used, nothing below 1 year.",
  grat_due: "Payment is due within 14 days of the last working day.",
  grat_warn_freezone:
    "DIFC and ADGM free zones use their own schemes (for example DEWS in DIFC). This calculator does not apply to them.",
  grat_warn_national:
    "UAE nationals are in the pension scheme instead of end-of-service gratuity. This calculator does not apply to them.",
  grat_unavailable: "Saving gratuity plans is not available yet on this database. The calculator works, but nothing is stored.",
  grat_demo_note: "Demo mode: changes are not saved.",
  grat_plans_label: "Employments",
  grat_new_plan: "New employment",
  grat_field_employer: "Employer",
  grat_field_start: "Start date",
  grat_field_end: "End date (blank = today)",
  grat_field_contract: "Contract type",
  grat_contract_unlimited: "Unlimited",
  grat_contract_limited: "Fixed term",
  grat_field_unpaid: "Unpaid leave days",
  grat_field_currency: "Currency",
  grat_field_stated: "Employer says still owed (optional)",
  grat_field_notes: "Notes",
  grat_wages: "Basic wage history",
  grat_wages_hint: "Basic wage per month only. The last entry is the wage the law method uses.",
  grat_wage_from: "Effective from",
  grat_wage_basic: "Basic per month",
  grat_wage_add: "Add wage",
  grat_payments: "Gratuity already paid",
  grat_payments_hint: "Payments received from this employer, with the date.",
  grat_pay_date: "Date",
  grat_pay_amount: "Amount",
  grat_pay_note: "Note",
  grat_pay_add: "Add payment",
  grat_remove: "Remove row",
  grat_save: "Save",
  grat_saving: "Saving...",
  grat_saved: "Saved.",
  grat_delete: "Delete employment",
  grat_delete_confirm: "Delete this employment? This cannot be undone.",
  grat_delete_yes: "Yes, delete",
  grat_cancel: "Cancel",
  grat_results: "Result",
  grat_enter_more: "Enter a start date and at least one basic wage to see the result.",
  grat_service: "Service counted",
  grat_service_value: "{whole} years and {extra} days",
  grat_entitlement: "Entitlement (law method)",
  grat_paid: "Already paid",
  grat_outstanding: "Outstanding",
  grat_overpaid_by: "Paid more than the entitlement by {amount}.",
  grat_tier_first: "First 5 years at 21 days",
  grat_tier_second: "After year 5 at 30 days",
  grat_days: "{days} days",
  grat_total_days: "Total days of basic wage",
  grat_daily: "Daily wage (basic / 30)",
  grat_last_basic: "Last basic wage",
  grat_cap: "Cap: 24 months of basic wage",
  grat_cap_usage: "{pct}% of the cap",
  grat_cap_reached: "Cap reached: the entitlement is limited to 24 months of basic wage.",
  grat_accrual: "Accrues about {amount} per month from now.",
  grat_period_title: "Alternative: each period at its own wage",
  grat_period_note: "For comparison only. The law uses the last basic wage.",
  grat_period_total: "Period-accrual total",
  grat_period_diff: "Difference vs law method",
  grat_since_title: "Since the last payment",
  grat_since_none: "No payment recorded: the whole service is unpaid.",
  grat_since_from: "From {date}",
  grat_since_value: "{years} years of service, about {amount} accrued",
  grat_recon_title: "Employer's figure",
  grat_recon_match: "Matches the calculation.",
  grat_recon_lower: "The employer states {amount} less than the calculation.",
  grat_recon_higher: "The employer states {amount} more than the calculation.",
  grat_w_under_one_year: "Less than 1 year of service: no gratuity is due yet.",
  grat_w_cap_reached: "The 24-month cap applies.",
  grat_w_overpaid: "Payments exceed the calculated entitlement.",
  grat_w_unpaid_leave_exceeds: "Unpaid leave is larger than the service: nothing is counted.",
  grat_w_wage_before_start: "The first wage starts after the employment start: it is used for the earlier period too.",
  grat_w_payment_ignored: "A payment with an invalid date or amount was ignored.",
  grat_err_employer: "Enter the employer (1 to 120 characters).",
  grat_err_start: "Enter a valid start date.",
  grat_err_end: "The end date must be a valid date on or after the start date.",
  grat_err_contract: "Choose a contract type.",
  grat_err_unpaid_leave: "Unpaid leave must be a whole number of days, zero or more.",
  grat_err_wage: "Enter at least one basic wage with a valid date and an amount above zero.",
  grat_err_wage_count: "At most 50 wage entries.",
  grat_err_payment: "Each payment needs a valid date and an amount of zero or more.",
  grat_err_payment_count: "At most 100 payments.",
  grat_err_stated: "The employer figure must be zero or more.",
  grat_err_currency: "Choose a 3-letter currency code.",
  grat_err_notes: "Notes must be 2000 characters or fewer.",
  grat_err_signed_out: "You must be signed in.",
  grat_err_mfa: "Complete the two-step verification first.",
  grat_err_demo: "The demo account is read-only.",
  grat_err_not_found: "This employment was not found.",
  grat_err_save_failed: "The employment could not be saved. Try again.",
  grat_err_unavailable: "Gratuity plans are not available yet on this database.",
} as const;

export type GratuityKey = keyof typeof GRAT_EN;
