/**
 * English texts of the IRR (TRI) comparison tool. The `irr_*` keys are typed locally so the tool
 * does not depend on them being in `lib/i18n.ts`'s `TranslationKey` union yet (they are merged from
 * `.tmp-irr-keys.json`). `useIrrText` (components/irr-compare-text.ts) asks `t()` first and falls
 * back to these strings while a key is not merged.
 */
export const IRR_EN = {
  irr_nav_compare: "Compare returns",
  irr_title: "Compare returns (IRR / TRI)",
  irr_subtitle:
    "Put two savings plans or investments side by side on the same yardstick: the effective annual rate (IRR / TRI).",
  irr_print: "Print",
  irr_side_a: "Investment A",
  irr_side_b: "Investment B",
  irr_source_aria: "Data source for {side}",
  irr_source_manual: "Manual",
  irr_source_holding: "My investment",
  irr_field_initial: "Initial capital",
  irr_field_monthly: "Monthly saving",
  irr_field_final: "Final capital",
  irr_field_years: "Duration (years)",
  irr_err_required: "Enter a number.",
  irr_err_number: "This is not a valid number.",
  irr_err_negative: "Must be zero or more.",
  irr_err_final: "Must be greater than zero.",
  irr_err_years: "Enter a duration from 1 month to 100 years, in whole months (for example 20 or 1.5).",
  irr_err_nothing: "Enter an initial capital or a monthly saving.",
  irr_err_solver: "No rate could be computed from these figures.",
  irr_result_rate: "Effective annual rate",
  irr_result_deposits: "Total deposits",
  irr_result_interest: "Total interest",
  irr_result_final: "Final capital",
  irr_result_nominal: "Nominal annual rate: {rate}",
  irr_manual_note: "Deposits are made at the end of each month; monthly rate = (1 + r)^(1/12) - 1.",
  irr_manual_pending: "Fill in the four fields to see the rate.",
  irr_holding_label: "Investment",
  irr_holding_placeholder: "Choose an investment...",
  irr_holding_search: "Search your investments...",
  irr_holding_empty: "No investment found.",
  irr_holding_none: "You have no investments to compare yet.",
  irr_load_failed: "Your investments could not be loaded. You can still compare manual plans.",
  irr_holding_pending: "Choose one of your investments to see its rate.",
  irr_unavailable_badge: "Unavailable",
  irr_unavail_missing_purchase_price: "The purchase price is missing.",
  irr_unavail_missing_purchase_date: "The purchase date is missing.",
  irr_unavail_missing_value: "The current value is missing.",
  irr_unavail_unsupported_category: "This kind of asset is not supported yet.",
  irr_unavail_missing_fx: "An exchange rate is missing.",
  irr_unavail_no_sign_change: "The flows have no money in or no money out, so no rate exists.",
  irr_includes_title: "Included in the calculation",
  irr_inc_purchase: "Purchase",
  irr_inc_income: "Income",
  irr_inc_value: "Current value",
  irr_inc_financing: "Financing",
  irr_included: "included",
  irr_excluded: "not included",
  irr_warn_income:
    "Income (rent, dividends, coupons) is not included in the flows, so the rate may differ from the full return.",
  irr_warn_financing: "Financing is not included: the rate is computed on the full purchase price, without any loan.",
  irr_warn_multiple:
    "These flows change sign more than once, so more than one rate can fit. The figure shown is one solution: read it with care.",
  irr_warn_horizon:
    "The two horizons differ ({a} vs {b} years): rates over different periods are not directly comparable.",
  irr_warn_currency: "The currencies differ ({a} vs {b}): amounts are not converted.",
  irr_fail_no_sign_change: "No rate: the flows need both money in and money out.",
  irr_fail_not_enough_flows: "No rate: at least two dated flows over a non-zero period are needed.",
  irr_fail_no_solution: "No rate could be found for these flows.",
  irr_compare_title: "Comparison",
  irr_compare_pending: "Complete both sides to see the comparison.",
  irr_row_irr: "IRR (effective annual rate)",
  irr_row_in: "Money in",
  irr_row_out: "Money out",
  irr_row_gain: "Gain",
  irr_row_multiple: "Multiple",
  irr_row_horizon: "Horizon",
  irr_years_value: "{n} years",
  irr_diff_label: "Difference (A - B)",
  irr_diff_value: "{value} percentage points",
  irr_chart_title: "Cumulative net position",
  irr_chart_aria: "Line chart of the cumulative net position of both investments over time",
  irr_chart_summary: "{label}: starts at {start} and ends at {end} after {years} years.",
  irr_chart_x: "Years",
  irr_disclaimer:
    "IRR assumes cash flows are reinvested at the same rate, ignores risk and liquidity, and a goal-based rate is a required return, not a performance. Not investment advice.",
} as const;

export type IrrKey = keyof typeof IRR_EN;
