/**
 * English texts of the retirement simulator (`ret_*`). The full 9-language set lives in .tmp-ret-keys.json until it
 * is merged into the i18n files; until a key is merged `t()` returns the key itself and `useRetirementText` falls back
 * to the English below, so the UI never shows raw keys.
 */
export const RET_EN = {
  "ret_title": "Retirement passive income",
  "ret_subtitle": "How much to set aside each month to reach a target passive income, given what you already have. An illustration built on your own assumptions.",
  "ret_inputs_title": "Your inputs",
  "ret_current_age": "Current age",
  "ret_retirement_age": "Retirement age",
  "ret_income": "Desired net passive income per month (today's money)",
  "ret_return": "Estimated annual return",
  "ret_value_age": "{value} years",
  "ret_value_money": "{value} per month",
  "ret_value_pct": "{value} % a year",
  "ret_assumptions": "Assumptions",
  "ret_assumptions_hint": "Inflation, income method and starting assets",
  "ret_inflation": "Annual inflation",
  "ret_method": "Income method",
  "ret_method_swr": "Withdrawal rate (rule of thumb)",
  "ret_method_returns": "Returns only (capital untouched)",
  "ret_swr": "Withdrawal rate per year",
  "ret_categories": "Categories counted as investable",
  "ret_assets_hint": "Real Estate counts at its equity (value minus its own loan). Other debts are not subtracted. Vehicles and illiquid holdings are off by default.",
  "ret_assets_auto": "From your portfolio: {amount}",
  "ret_assets_override": "Own figure (replaces the portfolio total)",
  "ret_assets_used": "Starting assets used: {amount}",
  "ret_current_saving": "Your current monthly saving (optional)",
  "ret_err_title": "Check these inputs",
  "ret_err_ages": "The retirement age must be after the current age.",
  "ret_err_current_age": "Enter a current age between 0 and 100.",
  "ret_err_retirement_age": "Enter a retirement age up to 100.",
  "ret_err_income": "Enter a monthly income above zero.",
  "ret_err_return": "Enter a return between 0 % and 20 %.",
  "ret_err_returns_zero": "Living on returns only needs a return above 0 %.",
  "ret_err_inflation": "Enter an inflation rate between 0 % and 20 %.",
  "ret_err_swr": "Enter a withdrawal rate above 0 % and up to 20 %.",
  "ret_err_assets": "Enter starting assets of 0 or more.",
  "ret_err_saving": "Enter a monthly saving of 0 or more, or leave it empty.",
  "ret_live": "Required saving: {amount} per month over {years} years.",
  "ret_live_on_track": "On track: no extra monthly saving is needed.",
  "ret_hero_label": "Required saving per month",
  "ret_hero_detail": "Over {years} years ({months} months), deposited at the end of each month",
  "ret_on_track_title": "Already on track",
  "ret_on_track_text": "With these assumptions, the current assets are projected to reach {assets} by retirement, which is {surplus} above the target capital of {target}. No extra saving is needed.",
  "ret_target": "Target capital at retirement",
  "ret_target_hint_swr": "Income at retirement × 12 ÷ {rate} %",
  "ret_target_hint_returns": "Income at retirement × 12 ÷ {rate} % return",
  "ret_assets_grown": "Current assets at retirement",
  "ret_assets_grown_hint": "{assets} today, growing at {rate} % a year",
  "ret_gap": "Gap to close",
  "ret_gap_hint": "Target capital minus current assets at retirement",
  "ret_time": "Time to retirement",
  "ret_time_value": "{years} years ({months} months)",
  "ret_income_nominal": "Monthly income at retirement",
  "ret_income_nominal_hint": "Nominal. Equals {today} per month in today's money, after {rate} % inflation a year",
  "ret_effort_title": "Monthly effort",
  "ret_effort_more": "{delta} more per month than the saving entered ({current}).",
  "ret_effort_less": "{delta} less per month than the saving entered ({current}).",
  "ret_effort_equal": "Matches the saving entered ({current}).",
  "ret_sens_title": "Sensitivity",
  "ret_sens_caption": "Required monthly saving if the return or the inflation differs",
  "ret_sens_col_assumption": "Assumption",
  "ret_sens_col_saving": "Monthly saving",
  "ret_sens_return": "Return {rate} %",
  "ret_sens_inflation": "Inflation {rate} %",
  "ret_sens_current": "current",
  "ret_sens_na": "n/a",
  "ret_chart_title": "What the target is made of",
  "ret_seg_assets": "Current assets",
  "ret_seg_assetGrowth": "Growth of current assets",
  "ret_seg_contributions": "Monthly savings paid in",
  "ret_seg_contributionGrowth": "Growth of the savings",
  "ret_chart_summary": "Of {total} at retirement, {fromAssets} comes from current assets and their growth and {fromSavings} from the monthly savings and their growth.",
  "ret_summary_title": "How this is calculated",
  "ret_summary_swr": "The desired income of {today} a month is raised by {inflation} % inflation a year to {nominal} a month at retirement. The target capital is that income for 12 months divided by the {rate} % withdrawal rate. Current assets grow at {ret} % a year (effective rate, monthly compounding) and monthly deposits are made at the end of each month.",
  "ret_summary_returns": "The desired income of {today} a month is raised by {inflation} % inflation a year to {nominal} a month at retirement. The target capital is that income for 12 months divided by the {rate} % return, so the capital itself is never drawn down. Current assets grow at {ret} % a year (effective rate, monthly compounding) and monthly deposits are made at the end of each month.",
  "ret_disc_title": "Please note",
  "ret_disc_1": "This is an illustration built on your own assumptions. It is not advice and not a forecast.",
  "ret_disc_2": "Tax on withdrawals is not modelled. The income is treated as net, so enter a net (after-tax) figure.",
  "ret_disc_3": "Returns are not guaranteed, and real markets move up and down from year to year.",
  "ret_disc_4": "The 4 % rule is a rule of thumb, not a guarantee.",
  "ret_disc_5": "Inflation is the largest driver of the result. The sensitivity table shows how much it matters.",
  "ret_disc_6": "Pensions and state benefits are not included.",
} as const;

export type RetKey = keyof typeof RET_EN;
