/**
 * English texts of the asset Analysis tab (`an_*` keys). The full 9-language set lives in `tmp-i18n-analysis.json`
 * until it is merged into the i18n files; until a key is merged `t()` returns the key itself and
 * `useAnalysisText` falls back to the English below, so the UI never shows raw keys (same pattern as
 * `banking-brokerage-labels.ts`). GENERATED from the translation table: edit the JSON/table, not this file by hand.
 */
export const ANALYSIS_EN = {
  an_current_value: "Current value",
  an_value_history: "Value history",
  an_change_first: "Change since first record",
  an_high: "Highest",
  an_low: "Lowest",
  an_max_drawdown: "Maximum drawdown",
  an_drawdown_now: "Below the high now",
  an_volatility: "Volatility (annualised)",
  an_volatility_hint: "From recorded values; indicative",
  an_needs_history: "Needs at least three recorded values",
  an_empty_history_missing: "Not enough value history yet (at least two recorded values are needed).",
  an_empty_history_how: "Refresh the value or record a valuation from the Overview tab; each one adds a point.",
  an_info_only: "Informational only, not advice.",
  an_share_portfolio: "Share of portfolio",
  an_share_class: "Share of asset class",
  an_share_unavailable: "Portfolio totals not loaded",
  an_position: "Position",
  an_days: "{n} days",
  an_years_n: "{n} years",
  an_year: "Year",
  an_date: "Date",
  an_bluebook_carried_note: "The Blue Book is an instant valuation: each dot is a real valuation, and the line carries it forward until the next one so the three values can be compared over the whole period.",
  an_bluebook_carried_tip: "carried forward",
  an_cash_balance_history: "Balance history",
  an_cash_flows: "Monthly cash flow",
  an_cash_flows_scope: "Based on the last {n} imported transactions.",
  an_cash_flows_missing: "No imported transactions for this account, so monthly flows cannot be shown.",
  an_cash_flows_how: "Import a bank statement (PDF or CSV) from the Settings tab.",
  an_cash_avg_in: "Average monthly inflow",
  an_cash_avg_out: "Average monthly outflow",
  an_cash_avg_net: "Average monthly net",
  an_cash_avg_hint: "Last {n} months with data",
  an_cash_runway: "Months of runway",
  an_cash_runway_months: "{n} months",
  an_cash_runway_hint: "Balance over average outflow of the last {n} complete months",
  an_cash_runway_missing: "Needs a positive balance and imported outflows",
  an_cash_inflow: "Inflow",
  an_cash_outflow: "Outflow",
  an_cash_net: "Net",
  an_cash_top_spend: "Top spending",
  an_cash_top_spend_desc: "Outflows grouped by merchant; essential or discretionary by the same keyword rules as the Cash Flow page.",
  an_cash_spend_missing: "No spending found in the imported transactions.",
  an_cash_spend_total: "Total spending",
  an_cash_essential: "Essential",
  an_cash_discretionary: "Discretionary",
  an_cash_other: "Other",
  an_cash_statement: "Statement and balance date",
  an_cash_last_tx: "Last imported transaction",
  an_cash_last_tx_missing: "No statement imported yet",
  an_cash_balance_asof: "Balance as of",
  an_cash_age: "Age of the balance",
  an_cash_stale: "Older than one month",
  an_cash_balance_note: "Balance history starts on {from}.",
  an_crypto_value_cost: "Value and profit or loss",
  an_crypto_value_cost_desc: "Compared with the first recorded value; the purchase price is not stored for crypto holdings.",
  an_crypto_unit_price: "Price per coin",
  an_crypto_units: "{n} coins held",
  an_crypto_cost_basis: "Cost basis",
  an_crypto_cost_missing: "No purchase price stored, so profit or loss against cost cannot be computed.",
  an_crypto_risk: "Drawdown and volatility",
  an_crypto_held: "Held for",
  an_metal_spot: "Spot price and weight",
  an_metal_spot_desc: "{metal} holding valued against the last spot price.",
  an_metal_gold: "Gold",
  an_metal_silver: "Silver",
  an_metal_platinum: "Platinum",
  an_metal_weight: "Total weight",
  an_metal_fine: "{n} troy oz of pure metal",
  an_metal_spot_price: "Spot price",
  an_metal_per_oz: "per troy ounce",
  an_metal_spot_missing: "No spot price recorded yet; refresh the price from the Settings tab.",
  an_metal_spot_value: "Value at spot",
  an_metal_premium: "Premium over spot",
  an_metal_premium_stated: "Premium entered",
  an_metal_price_oz: "Value per fine ounce",
  an_metal_cost: "Purchase cost",
  an_metal_cost_missing: "Not stored for metals; compare with the first recorded value below.",
  an_metal_weight_missing: "The weight per piece is not filled in, so weight, spot value and premium cannot be computed.",
  an_metal_weight_how: "Edit the asset and enter the weight per bar or coin and its purity.",
  an_metal_value_history: "Value history",
  an_eq_perf: "Performance against cost",
  an_eq_perf_desc: "Value of the shares still held against their average cost.",
  an_eq_perf_missing: "No buy trades recorded, so the cost of the position is unknown.",
  an_eq_perf_how: "Import your broker trades or add them from the Settings tab.",
  an_eq_cost: "Cost of open shares",
  an_eq_gain: "Unrealised gain or loss",
  an_eq_total_return: "Total return incl. income",
  an_eq_total_return_hint: "(gain + income) / cost",
  an_eq_xirr: "Money-weighted return",
  an_eq_xirr_desc: "Annualised rate that reflects when each purchase, sale and dividend happened (XIRR), with the current value as the final inflow.",
  an_eq_xirr_rate: "Annualised return (XIRR)",
  an_eq_xirr_flows: "Computed from {n} dated flows",
  an_eq_xirr_no_trades: "No trades recorded",
  an_eq_xirr_mixed: "Trades are in another currency than the holding",
  an_eq_xirr_no_solution: "No rate fits these flows",
  an_eq_xirr_short: "Held for under 30 days; an annual rate would mislead",
  an_eq_income_12m: "Income, last 12 months",
  an_eq_income_total: "{amount} received in total",
  an_eq_income_missing: "No dividends or income recorded; add them in Settings to see yield.",
  an_eq_yield_value: "Income yield on value",
  an_eq_yield_cost: "Income yield on cost",
  an_eq_risk: "Risk and position",
  an_vehicle_curve: "Depreciation curve",
  an_vehicle_curve_desc: "Market value, purchase price, the Blue Book and the modelled depreciation from the rates in force.",
  an_vehicle_curve_missing: "No valuation, purchase price or Blue Book value recorded yet.",
  an_vehicle_curve_how: "Record the purchase price and date, a valuation or a Blue Book value from the Overview tab.",
  an_vehicle_model_line: "Modelled depreciation",
  an_vehicle_residual: "Residual value",
  an_vehicle_residual_pct: "Residual value",
  an_vehicle_residual_hint: "Current value / purchase price",
  an_vehicle_price_missing: "Needs a purchase price",
  an_vehicle_value_lost: "Value lost since purchase",
  an_vehicle_lost_month: "Value lost per month",
  an_vehicle_months: "Over {n} months",
  an_vehicle_date_missing: "Needs a purchase date",
  an_vehicle_vs_bb: "Market value vs Blue Book",
  an_vehicle_bb_missing: "No Blue Book valuation recorded",
  an_vehicle_tco: "Cost of ownership",
  an_vehicle_tco_desc: "Value lost plus running costs (expenses and the lump-sum cost fields).",
  an_vehicle_tco_total: "Total cost of ownership",
  an_vehicle_tco_month: "Cost per month",
  an_vehicle_tco_km: "Cost per km",
  an_vehicle_km_hint: "Over the odometer reading, not only your own distance",
  an_vehicle_km_missing: "Needs the mileage and a purchase price",
  an_vehicle_running: "Running costs",
  an_vehicle_expenses_hint: "Log expenses in the Expenses tab for a fuller picture",
  an_vehicle_legend_dep: "Value lost: {share} of the cost",
  an_vehicle_legend_run: "Running costs: {amount}",
  an_vehicle_by_category: "Running costs by category",
  an_vehicle_entries: "{n} entries",
  an_vehicle_expenses_missing: "No dated expenses logged for this vehicle.",
  an_vehicle_expenses_how: "Add fuel, maintenance, insurance and other costs in the Expenses tab.",
  an_re_yield: "Yield on cost",
  an_re_yield_desc: "Annual rent of the contract in force against the all-in purchase cost (price plus fees).",
  an_re_rent_missing: "No tenancy contract in force is recorded, so the yield cannot be computed.",
  an_re_rent_how: "Upload the tenancy contract from the Tenancy tab.",
  an_re_rent_annual: "Annual rent",
  an_re_yield_gross: "Gross yield on cost",
  an_re_on_cost: "On a cost of {amount}",
  an_re_yield_net: "Net yield on cost",
  an_re_net_hint: "After {amount} of expenses in the last 12 months",
  an_re_yield_value: "Yield on current value",
  an_re_equity: "Equity build-up and loan to value",
  an_re_equity_desc: "Market value minus the loan balance from the amortisation schedule, at each recorded valuation.",
  an_re_series_missing: "At least two recorded valuations are needed to show the build-up.",
  an_re_series_how: "Record valuations from the Overview tab; add the loan in the Settings tab to see loan to value.",
  an_re_equity_now: "Equity now",
  an_re_build_up: "Equity build-up",
  an_re_build_hint: "Since the first valuation on {date}",
  an_re_loan_now: "Loan balance",
  an_re_no_loan: "No loan recorded",
  an_re_ltv_now: "Loan to value",
  an_re_market: "Market value",
  an_re_equity_line: "Equity",
  an_re_loan_line: "Loan balance",
  an_re_ltv_line: "Loan to value over time",
  an_pe_multiples: "Fund multiples",
  an_pe_multiples_desc: "Actuals only: projected distributions are not counted.",
  an_pe_paid_missing: "No capital paid in yet, so the fund multiples cannot be computed.",
  an_pe_paid_how: "Mark capital calls as paid (or enter the called capital) in the Settings tab.",
  an_pe_dpi_hint: "Distributions / paid-in",
  an_pe_rvpi_hint: "Current value / paid-in",
  an_pe_tvpi_hint: "DPI + RVPI",
  an_pe_irr: "Net IRR",
  an_pe_irr_hint: "Dated calls and distributions, with the current value as the final inflow",
  an_pe_irr_no_paid_in: "No paid-in capital",
  an_pe_irr_undated_flows: "Needs dated paid calls and dated distributions",
  an_pe_irr_no_solution: "No rate fits these flows",
  an_pe_jcurve: "J-curve",
  an_pe_jcurve_desc: "Cumulative net cash flow: paid calls out, distributions in.",
  an_pe_ledger_missing: "Fewer than two dated cash flows are recorded, so there is no curve yet.",
  an_pe_ledger_how: "Add paid capital calls with their dates and distributions in the ledger (Settings tab).",
  an_pe_paid_in: "Paid-in capital",
  an_pe_distributed: "Distributions received",
  an_pe_trough: "Deepest point",
  an_pe_with_nav: "Net position incl. current value",
  an_pe_with_nav_hint: "Cumulative cash flow plus the current value",
  an_pe_cumulative: "Cumulative net cash flow",
  an_pe_unfunded: "Unfunded commitment",
  an_pe_unfunded_desc: "Pending capital calls in date order and what remains to be called after each.",
  an_pe_commitment_missing: "No commitment amount or scheduled calls recorded.",
  an_pe_commitment_how: "Enter the commitment and the call schedule in the Settings tab.",
  an_pe_commitment: "Commitment",
  an_pe_unfunded_total: "Unfunded",
  an_pe_called_share: "Called so far",
  an_pe_unscheduled: "Not yet scheduled",
  an_pe_unscheduled_hint: "Unfunded commitment with no dated call",
  an_pe_no_pending: "No pending capital call is scheduled.",
  an_pe_overdue: "Overdue",
  an_pe_left_after: "{amount} left to call after",
  an_scpi_value: "Value against capital invested",
  an_scpi_value_desc: "Withdrawal value of the shares against what was paid at subscription, entry fee included.",
  an_scpi_price_missing: "No subscription price recorded, so value against capital invested cannot be shown.",
  an_scpi_price_how: "Enter the subscription price and the number of shares in the Settings tab.",
  an_scpi_invested: "Capital invested",
  an_scpi_fees: "Including {amount} of entry fees",
  an_scpi_gap: "Value minus invested",
  an_scpi_withdrawal_gap: "Withdrawal vs subscription price",
  an_scpi_prices: "Subscription {sub}, withdrawal {wd}",
  an_scpi_withdrawal_missing: "No withdrawal value or entry fee recorded",
  an_scpi_distribution: "Distribution rate by year",
  an_scpi_distribution_desc: "Dividends received over capital invested, next to the distribution rate you recorded.",
  an_scpi_dividends_missing: "No dividend or distribution rate recorded yet.",
  an_scpi_dividends_how: "Add the dividends received and the yearly rates in the Settings tab.",
  an_scpi_received: "Dividends received",
  an_scpi_total_return: "Total return on capital",
  an_scpi_total_return_hint: "(value + dividends - invested) / invested",
  an_scpi_realised_rate: "Realised rate",
  an_scpi_stated_rate: "Recorded rate",
  an_scpi_partial: "(part year)",
  an_scpi_share_history: "Value per share over time",
  an_scpi_share_line: "Value per share",
  an_scpi_share_missing: "At least two recorded values are needed to show the value per share over time.",
  an_scpi_share_how: "Update the withdrawal value from the Settings tab when the company publishes a new one; each update adds a point.",
  an_co_stake: "Stake and valuation",
  an_co_stake_desc: "Your ownership of the company and its entered valuation.",
  an_co_stake_missing: "No ownership percentage or company value recorded.",
  an_co_stake_how: "Edit the company and enter the ownership and its valuation.",
  an_co_ownership: "Ownership",
  an_co_ownership_missing: "Not recorded",
  an_co_value: "Company value (100%)",
  an_co_stake_value: "Value of your stake",
  an_co_valuation_date: "Valuation date",
  an_co_age: "{n} days ago",
  an_co_date_missing: "Date not recorded",
  an_co_valuation_history: "Valuation history",
  an_co_more: "Holdings and accounts",
  an_co_change: "Change in stake value",
  an_co_held_assets: "Assets held through it",
  an_co_accounts: "Linked bank accounts",
  an_co_accounts_total: "{amount} in total",
  an_co_accounts_missing: "Account figures not loaded",
  an_co_dividends: "Dividends received",
  an_co_dividends_missing: "Dividends are not tracked for companies yet",
  an_su_rounds: "Funding rounds",
  an_su_rounds_desc: "Price per share by round, step-ups and the multiple on your cost.",
  an_su_rounds_missing: "No funding round recorded yet, so the holding is valued at cost.",
  an_su_rounds_how: "Add funding rounds (date, name, price per share, post-money) in the Settings tab.",
  an_su_cost: "Cost basis",
  an_su_cost_missing: "Average cost per share not entered",
  an_su_multiple: "Multiple on cost",
  an_su_multiple_hint: "Current value / cost basis",
  an_su_post_money: "Post-money valuation",
  an_su_post_missing: "No post-money valuation entered",
  an_su_price_line: "Price per share",
  an_su_round: "Round",
  an_su_price: "Price",
  an_su_step_up: "Step-up",
  an_su_dilution: "Ownership and dilution",
  an_su_dilution_desc: "Your share of the company after each round, assuming your number of shares did not change.",
  an_su_dilution_missing: "Needs at least two rounds with a post-money valuation.",
  an_su_dilution_how: "Enter the post-money valuation for each round in the Settings tab.",
  an_su_own_first: "Ownership, first round",
  an_su_own_last: "Ownership, latest round",
  an_su_dilution_change: "Change in ownership",
  an_ex_appraisals: "Appraisal history",
  an_ex_appraisals_desc: "Recorded market values against the purchase price.",
  an_ex_appraisals_missing: "Fewer than two recorded values, so there is no history to show yet.",
  an_ex_appraisals_how: "Refresh the market value (or record an appraisal) from the Overview tab; each adds a point.",
  an_ex_appraisal_line: "Market value",
  an_ex_purchase: "Purchase price",
  an_ex_purchase_missing: "Not entered",
  an_ex_gain: "Gain or loss vs purchase",
  an_ex_cagr: "Annualised growth",
  an_ex_cagr_hint: "Compound rate since purchase",
  an_ex_cover: "Insurance and holding period",
  an_ex_insured: "Insured value",
  an_ex_insured_missing: "Not tracked yet: the insured value is not stored for this asset.",
  an_ex_insured_gap: "Insured minus market value",
  an_ex_insured_gap_hint: "Positive when the insured value is above the market value",
  an_ex_held: "Holding period",
  an_ex_date_missing: "Purchase date not recorded",
  an_li_payoff: "Payoff outlook",
  an_li_payoff_desc: "Projected from the balance, the interest rate and the monthly payment you entered.",
  an_li_balance: "Balance owed",
  an_li_months_left: "Months to payoff",
  an_li_payoff_date: "Payoff date",
  an_li_interest_left: "Interest still to pay",
  an_li_gap_no_payment: "No monthly payment entered",
  an_li_gap_no_rate: "No interest rate entered",
  an_li_gap_never: "The monthly payment does not cover the interest, so the balance does not fall",
  an_li_gap_no_balance: "No balance owed",
  an_li_how: "Edit the liability and enter the interest rate and the monthly payment.",
  an_li_utilisation: "Card utilisation: {pct} of the credit limit",
  an_li_schedule: "Remaining schedule",
  an_li_schedule_desc: "Payments from today at the entered rate; the last payment is shortened to the balance.",
  an_li_schedule_missing: "No schedule can be projected from the data entered.",
  an_li_interest_share: "Interest share of remaining payments",
  an_li_interest_share_hint: "Interest / (principal + interest)",
  an_li_interest_next: "Interest in the next payment",
  an_li_interest_next_hint: "Share of that payment that is interest",
  an_li_paid_estimate: "Interest paid so far (estimate)",
  an_li_paid_hint: "Payments since the first recorded balance minus principal repaid",
  an_li_paid_missing: "Needs a monthly payment and at least a recorded balance above today's",
  an_li_balance_line: "Balance owed",
  an_li_col_payment: "Payment",
  an_li_col_interest: "Interest",
  an_li_col_principal: "Principal",
  an_li_col_balance: "Balance",
  an_li_history: "Balance history",
  an_li_repaid: "Repaid since first record",
  an_li_repaid_hint: "Since {date}",
  an_av_premiums: "Premiums against value",
  an_av_premiums_desc: "Total premiums paid against the contract value. A difference, not a performance figure: the dates of premiums are not used.",
  an_av_premiums_missing: "The total premiums paid is not recorded.",
  an_av_premiums_how: "Edit the contract and enter the total premiums paid.",
  an_av_paid: "Premiums paid",
  an_av_difference: "Value minus premiums",
  an_av_scheduled: "Scheduled premiums per year",
  an_av_scheduled_hint: "From the scheduled amount and frequency",
  an_av_scheduled_missing: "No scheduled premiums",
  an_av_timeline: "{years}-year milestone",
  an_av_opened_missing: "The opening date is not recorded, so the timeline cannot be shown.",
  an_av_opened_how: "Edit the contract and enter the opening date.",
  an_av_opened: "Opened {date}",
  an_av_target: "Milestone {date}",
  an_av_reached: "Reached {n} days ago.",
  an_av_remaining: "{n} days remaining ({pct} of the period elapsed).",
  an_av_allocation: "Allocation",
  an_av_holdings_note: "Split stated on the contract; {n} holdings entered (full breakdown in the Overview tab).",
  an_av_holdings_missing: "Split stated on the contract; no individual holdings entered.",
} as const;

export type AnalysisKey = keyof typeof ANALYSIS_EN;
