/* English text for the landing page. Fallback used until the same keys are merged into src/lib/i18n.ts (see landing-copy.tsx). */
export const LANDING_EN = {
  landing_tagline_v2: "Your private wealth office",
  landing_body_v2: "Real estate, companies, funds, art, vessels and cash, recorded in one private register and seen in one view. Built for people whose holdings do not fit a bank app.",
  landing_secondary: "See what it holds",
  landing_assets_eyebrow: "Holdings",
  landing_assets_title: "Every kind of asset, in one register.",
  landing_assets_intro: "From a villa to a private jet, from a family holding company to a bullion vault: each is recorded in its own terms and brought together at today's value.",
  landing_asset_yachts: "Yachts & aircraft",
  landing_asset_yachts_d: "Vessels and aircraft, recorded at current market value.",
  landing_asset_art: "Art & collectibles",
  landing_asset_art_d: "Paintings, watches, wine and other pieces, with the purchase price set against today's value.",
  landing_asset_pe_d: "Funds and direct stakes at net asset value, less the capital still to be called.",
  landing_asset_scpi: "SCPI",
  landing_asset_scpi_d: "French property funds, held alongside your other real estate.",
  landing_asset_av: "Assurance-Vie",
  landing_asset_av_d: "French life-insurance contracts, kept in the same register.",
  landing_asset_entities: "Companies & entities",
  landing_asset_entities_d: "Trusts, foundations, SPVs and operating companies, seen through to what they hold.",
  landing_asset_re_d: "Property at market value, with the loan against it and the equity that remains.",
  landing_asset_metals_d: "Gold, silver and other bullion, priced from the live market.",
  landing_proof_eyebrow: "In practice",
  landing_proof_title: "Plain statements about how it works.",
  landing_proof_privacy: "Privacy mode",
  landing_proof_privacy_d: "Hide every amount with one switch when someone else can see your screen.",
  landing_proof_auth: "Passkeys and multi-factor sign-in",
  landing_proof_auth_d: "Sign in with a passkey or an authenticator app, and confirm again before sensitive changes.",
  landing_proof_coowner: "Co-owner approvals",
  landing_proof_coowner_d: "When an asset is shared, a change to it waits for the other owner's approval.",
  landing_proof_lang: "Nine languages",
  landing_proof_lang_d: "English, French, Arabic, German, Spanish, Hindi, Italian, Russian and Chinese, with right-to-left layout for Arabic.",
  landing_proof_fx: "Multi-currency, with FX attribution",
  landing_proof_fx_d: "Each holding stays in its own currency. When a total moves, you can see how much came from the exchange rate and how much from the asset.",
  landing_closing_title: "Begin with what you hold today.",
  landing_closing_body: "Sign in to open your register. Nothing here is advice, and nothing is a promise of return.",
  landing_disclaimer: "Opes Wealth is a record-keeping and reporting tool. It does not provide investment, tax or legal advice.",
} as const;
