import { describe, expect, it } from "vitest";
import { describeOcrLayout, maskText } from "./ocr-layout";
import type { OcrDocument } from "./ocr-types";

const ALLOWED = new Set([
  "date", "value", "balance", "debit", "credit", "description", "details", "particulars", "transaction",
  "withdrawal", "withdrawals", "deposit", "deposits", "amount", "paid", "in", "out", "brought", "forward",
  "carried", "cr", "dr", "ccy", "currency", "account", "statement", "period", "opening", "closing", "total",
  "page", "of", "ref", "reference", "narrative", "narration", "remarks",
]);

const doc: OcrDocument = {
  pages: [
    {
      lines: [
        "HSBC Bank Middle East Limited",
        "Mr Jonathan Whitfield-Reyes",
        "Flat 1204, Marina Heights Tower, Dubai Marina",
        "IBAN AE070331234567890123456",
        "Statement of Account 01 Feb 2026 to 28 Feb 2026",
        "Closing balance 12,345.67 CR",
      ],
      tables: [
        {
          rows: [
            ["Date", "Transaction details", "Withdrawals", "Deposits", "Balance"],
            ["", "B/F", "", "", "9,100.00 CR"],
            ["02/02/2026", "CARREFOUR MALL OF EMIRATES", "40.00", "", "9,060.00 CR"],
            ["03-02-2026", "SALARY ACME TRADING LLC", "", "5,000.00", "14,060.00 CR"],
            ["04/02/2026", "ATM JBR", "1,000.00", "", "13,060.00"],
            ["05/02/2026", "C/F", "", "", "13,060.00"],
            ["06/02/2026", "EXTRA ROW", "1.00", "", "13,059.00"],
            ["07/02/2026", "LAST BUT ONE", "1.00", "", "13,058.00"],
            ["", "Closing balance", "", "", "13,058.00 CR"],
          ],
        },
      ],
    },
  ],
};

describe("maskText", () => {
  it("maps every digit to 9 and keeps punctuation structure", () => {
    expect(maskText("02/02/2026")).toBe("99/99/9999");
    expect(maskText("12,345.67 CR")).toBe("99,999.99 CR");
    expect(maskText("-1,000.00")).toBe("-9,999.99");
  });

  it("replaces non-allow-listed words with x of the same length and keeps allow-listed ones case-insensitively", () => {
    expect(maskText("Jonathan Whitfield-Reyes")).toBe("xxxxxxxx xxxxxxxxx-xxxxx");
    expect(maskText("Date BALANCE Brought forward")).toBe("Date BALANCE Brought forward");
  });

  it("keeps b/f and c/f only as standalone tokens", () => {
    expect(maskText("B/F")).toBe("B/F");
    expect(maskText("c/f 9.00")).toBe("c/f 9.99");
    expect(maskText("ab/fx")).toBe("xx/xx");
    expect(maskText("b/fx")).toBe("x/xx");
  });

  it("masks mixed alphanumerics fully (IBAN style) and non-Latin text", () => {
    expect(maskText("AE070331234567890123456")).toBe("x" + "x" + "9".repeat(21));
    expect(maskText("in2")).toBe("xx9");
    expect(maskText("أحمد ١٢٣")).toBe("xxxx 999");
  });
});

describe("describeOcrLayout", () => {
  const text = describeOcrLayout(doc);

  it("never emits a digit other than 9, nor a non-allow-listed word", () => {
    // The structural counts ("Page 1", "9 rows") are generated by us; strip our own labels first.
    const body = text
      .split("\n")
      .filter((l) => /^\s+\d+: /.test(l))
      .map((l) => l.replace(/^\s+\d+: /, ""))
      .join("\n");
    expect(body).not.toMatch(/[0-8]/);
    for (const w of body.match(/[A-Za-z]+/g) ?? []) {
      const ok = /^x+$/.test(w) || ALLOWED.has(w.toLowerCase()) || ["b", "f", "c"].includes(w.toLowerCase());
      expect(ok, `leaked word: ${w}`).toBe(true);
    }
    for (const leak of ["Jonathan", "Whitfield", "Marina", "Dubai", "Tower", "AE07", "0331", "CARREFOUR", "SALARY", "ACME", "HSBC", "1204"]) {
      expect(text).not.toContain(leak);
    }
  });

  it("keeps the structure: formats, headers, counts, first and last table rows", () => {
    expect(text).toContain("1 page(s)");
    expect(text).toContain("6 lines, 1 tables");
    expect(text).toContain("9 rows, 5 columns");
    expect(text).toContain("Date | Transaction details | Withdrawals | Deposits | Balance");
    expect(text).toContain("99/99/9999 | xxxxxxxxx xxxx OF xxxxxxxx | 99.99 |  | 9,999.99 CR");
    expect(text).toContain("99-99-9999");
    expect(text).toContain("B/F");
    expect(text).toContain("Closing balance |  |  | 99,999.99 CR");
    expect(text).toContain("...");
    expect(text).toContain("Statement of Account 99 xxx 9999 xx 99 xxx 9999");
  });

  it("truncates to maxChars and says so", () => {
    const small = describeOcrLayout(doc, { maxChars: 200 });
    expect(small.length).toBeLessThanOrEqual(200);
    expect(small.endsWith("[truncated]")).toBe(true);
    expect(describeOcrLayout(doc, { maxChars: 100000 })).not.toContain("[truncated]");
  });

  it("defaults to a 4000 char cap", () => {
    const big: OcrDocument = { pages: Array.from({ length: 60 }, () => ({ lines: Array(40).fill("Some words here 12.00"), tables: [] })) };
    const out = describeOcrLayout(big);
    expect(out.length).toBeLessThanOrEqual(4000);
    expect(out).toContain("[truncated]");
  });

  it("lists header-like lines found beyond the first 40 lines", () => {
    const lines = Array(45).fill("filler text").concat(["Date Description Balance"]);
    const out = describeOcrLayout({ pages: [{ lines, tables: [] }] });
    expect(out).toContain("Header-like lines further down");
    expect(out).toContain("46: Date Description Balance");
  });
});
