-- 0034_notifications.sql
-- Opes Wealth: in-app notifications. First use: tell the REQUESTER of a change to a co-owned
-- asset when a co-owner approves or rejects it, or when it is auto-applied after 7 days.
--
-- WRITTEN, NOT APPLIED. Steve applies this in the Supabase SQL editor. Nothing in the repo
-- runs it. Until it is applied the app keeps working: notification inserts/reads fail with
-- "relation does not exist" (42P01 / PGRST205) and the code swallows that.
--
-- Rows are created by server code with the service role (bypasses RLS), so there is NO
-- insert policy for authenticated users. A signed-in user can read, mark as read and delete
-- only their own rows. `data` holds structured params (asset name, responder name), never
-- translated text: the UI builds the sentence in the viewer's language.
--
-- Idempotent: safe to re-run. Run 0032 again afterwards if you want the demo-mode deny
-- policies re-generated by its loop; this file also adds them for this table directly.

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  kind text not null check (kind in ('change_approved', 'change_rejected', 'change_auto_applied')),
  asset_id uuid references public.assets (id) on delete set null,
  request_id uuid,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_profile_created_idx
  on public.notifications (profile_id, created_at desc);
create index if not exists notifications_profile_unread_idx
  on public.notifications (profile_id) where read_at is null;

alter table public.notifications enable row level security;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
  on public.notifications for select to authenticated
  using (profile_id = (select auth.uid()));

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own"
  on public.notifications for update to authenticated
  using (profile_id = (select auth.uid()))
  with check (profile_id = (select auth.uid()));

drop policy if exists "notifications_delete_own" on public.notifications;
create policy "notifications_delete_own"
  on public.notifications for delete to authenticated
  using (profile_id = (select auth.uid()));

-- No insert policy: only the service role (server code) creates notifications.

-- Column-level guard: the only column a browser session may change is read_at.
revoke update on public.notifications from anon, authenticated;
grant update (read_at) on public.notifications to authenticated;

-- Demo account: read-only, like every other table (see 0032).
drop policy if exists demo_readonly_insert on public.notifications;
drop policy if exists demo_readonly_update on public.notifications;
drop policy if exists demo_readonly_delete on public.notifications;
create policy demo_readonly_insert on public.notifications as restrictive for insert to authenticated with check (not public.is_demo_user());
create policy demo_readonly_update on public.notifications as restrictive for update to authenticated using (not public.is_demo_user()) with check (not public.is_demo_user());
create policy demo_readonly_delete on public.notifications as restrictive for delete to authenticated using (not public.is_demo_user());
